version: "2.4"

################################################################################

services:
  ri-gvlab: # image name : PROJECT_ri-gvlab
    container_name: ri-gvlab # container name: ri-gvlab
    runtime: nvidia
    privileged: true
    environment:
      # Display X Server GUI.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=11.0
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    shm_size: '8gb' # Docker イメージ構築時に割り当てる共有メモリの容量
    volumes:
      # Mount the project directory.
      - ../:/root/Research_Internship_at_GVlab
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: tail -f /dev/null # コンテナ起動時に実行するコマンド